version: '3.9'
services:
  auth-service:
    image: mercari-repo/sodium-burner-466106-g3/auth-service:latest
    ports:
      - "4000:4000"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${AUTH_DB_NAME}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_DIALECT=postgres
    - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  cart-service:
    image: mercari-repo/sodium-burner-466106-g3/cart:latest
    ports:
      - "3001:3001"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${CART_DB_NAME}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_DIALECT=postgres
    - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  product-service:
    image: mercari-repo/sodium-burner-466106-g3/product:latest
    ports:
      - "3000:3000"
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${PRODUCT_DB_NAME}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_DIALECT=postgres
    - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped

  gateway-service:
    image: mercari-repo/sodium-burner-466106-g3/gateway-service:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    restart: unless-stopped